{% set name = "google-cloud-secret-manager" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-secret-manager-{{ version }}.tar.gz
  sha256: fd13a780d64995dea203c5a36c92cb373bb9bc558f15435d4e291cef490d910e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - google-api-core >=1.22.2,<2.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - libcst >=0.2.5
    - proto-plus >=1.4.0
    - python >=3.6

test:
  imports:
    - google
    - google.cloud
    - google.cloud.secretmanager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-secret-manager
  summary: Secret Manager API API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vladsaveliev
    - xylar
