{% set name = "google-cloud-secret-manager" %}
{% set version = "2.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-secret-manager-{{ version }}.tar.gz
  sha256: 1b6bf2863da96cdcb0184dbf413c8dbe261039cb008f8291f2f21c1a1bcce5ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.28.0,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - proto-plus >=1.4.0

test:
  imports:
    - google
    - google.cloud
    - google.cloud.secretmanager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-secret-manager
  summary: Secret Manager API API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vladsaveliev
    - xylar
